version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    command: sh -c "cd app-frontend && npm start"
    ports:
      - "8000:3000"
    depends_on:
      - db
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    tty: true
    command: sh -c "cd app-backend && npm start"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=develop
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "3300:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
